# Generated by Django 5.0.4 on 2024-04-22 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='收件人姓名')),
                ('phone_number', models.CharField(max_length=20, verbose_name='联系电话')),
                ('state_province', models.CharField(max_length=100, verbose_name='省/州')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('street_address', models.CharField(max_length=255, verbose_name='街道地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认地址')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='配送说明')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='校区名称')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='类别名')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='书名')),
                ('author', models.CharField(max_length=128, verbose_name='作者')),
                ('image', models.CharField(default='/media/book_img/default.png', max_length=128, verbose_name='图片')),
                ('detail', models.CharField(max_length=255, verbose_name='详情')),
                ('status', models.CharField(max_length=128, verbose_name='使用情况')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranapp.type', verbose_name='类别')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(default='/media/avatar/default.png', max_length=128, verbose_name='头像')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranapp.campus', verbose_name='所属校区')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerid', to='tranapp.userinfo', verbose_name='买家')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='tranapp.userinfo', verbose_name='卖家')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('status', models.IntegerField(choices=[(0, '待收货'), (1, '已确认'), (2, '我的售卖')], default=0, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tranapp.address', verbose_name='配送地址')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranapp.book', verbose_name='书籍')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_seller', to='tranapp.userinfo', verbose_name='卖家')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='tranapp.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('sessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranapp.session', verbose_name='会话id')),
                ('recipientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecipient', to='tranapp.userinfo', verbose_name='接收者')),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='tranapp.userinfo', verbose_name='发送者')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranapp.book', verbose_name='书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranapp.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranapp.userinfo', verbose_name='发布者'),
        ),
    ]
