# Generated by Django 5.0.4 on 2024-04-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='用户576300', max_length=128, verbose_name='昵称'),
        ),
    ]
