# Generated by Django 5.0.4 on 2024-04-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranapp', '0003_book_price_alter_userinfo_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=1, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='用户599123', max_length=128, verbose_name='昵称'),
        ),
    ]
