# Generated by Django 5.0.4 on 2024-04-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranapp', '0005_address_userinfo_alter_userinfo_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state_province',
            field=models.CharField(max_length=100, null=True, verbose_name='省/州'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='用户190659', max_length=128, verbose_name='昵称'),
        ),
    ]
