# Generated by Django 5.0.4 on 2024-04-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranapp', '0007_remove_address_city_remove_address_state_province_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '地址', 'verbose_name_plural': '地址'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '二手书', 'verbose_name_plural': '二手书'},
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': '校区', 'verbose_name_plural': '校区'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '购物车条目', 'verbose_name_plural': '购物车条目'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '消息记录', 'verbose_name_plural': '消息记录'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': '临时会话管理', 'verbose_name_plural': '临时会话管理'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': '二手书类别', 'verbose_name_plural': '二手书类别'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '待支付'), (1, '待收货'), (2, '已确认'), (3, '我的售卖')], default=0, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='用户890701', max_length=128, verbose_name='昵称'),
        ),
    ]
