# Generated by Django 5.0.4 on 2024-04-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranapp', '0008_alter_address_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '待支付'), (1, '已支付')], default=0, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='用户247433', max_length=128, verbose_name='昵称'),
        ),
    ]
