# Generated by Django 5.0.4 on 2024-04-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranapp', '0010_banner_alter_userinfo_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.IntegerField(choices=[(1, '未出售'), (2, '已出售')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='用户246053', max_length=128, verbose_name='昵称'),
        ),
    ]
