# Generated by Django 5.0.4 on 2024-05-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranapp', '0013_alter_userinfo_nickname_article_articlecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='name',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='用户439630', max_length=128, verbose_name='昵称'),
        ),
    ]
