# Generated by Django 5.0.4 on 2024-05-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranapp', '0014_rename_name_articlecomment_sender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '小程序端用户', 'verbose_name_plural': '小程序端用户'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='用户543278', max_length=128, verbose_name='昵称'),
        ),
    ]
