# Generated by Django 5.0.4 on 2024-05-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranapp', '0015_alter_article_options_alter_userinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(default=10.0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='用户951284', max_length=128, verbose_name='昵称'),
        ),
    ]
